apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachejm
  labels:
    app: apachejm
spec:
  selector:
    matchLabels:
      app: apachejm
  template:
    metadata:
      labels:
        app: apachejm
    spec:
      containers:
      - name: apachejm
        image: 172.30.1.1:5000/jenkins/apachejm
        ports:
        - containerPort: 80
        #command: ["/usr/sbin/init", "-c"]
          #capabilities:
          #  drop:
          #  - KILL
          #  - MKNOD
          #  - SETGID
          #  - SETUID
        #privileged: true
        command: ["/usr/sbin/httpd","-D","FOREGROUND"]
        #command: ["/usr/sbin/init", "-c"]
        #command: ["/usr/sbin/httpd","-D","FOREGROUND"]
        #runAsUser: 1000280000


---
apiVersion: v1
kind: Service
metadata:
  name: apachejm-service
spec:
  selector:
    app: apachejm
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
---
apiVersion: v1
kind: Route
metadata:
  name: apachejm-route
spec:
  to:
    kind: Service
    name: apachejm-service
